# Generated by Django 5.0.4 on 2025-01-16 07:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('payment', '0001_initial'),
        ('service', '0001_initial'),
        ('status', '0001_initial'),
        ('subService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя пациента')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия пациента')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Дата рождение')),
                ('phone', models.CharField(max_length=13, verbose_name='Тел.Номер')),
                ('appointment_date', models.DateField(default=datetime.date.today, verbose_name='Дата назначение')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало дата')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончание')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.status')),
                ('subService', models.ManyToManyField(blank=True, related_name='appointments', to='subService.subservice')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subService.subservice')),
            ],
        ),
    ]
