# Generated by Django 5.0.4 on 2025-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название услуга')),
                ('description', models.TextField(verbose_name='Описание услуга')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
